xperiment/lab/urls.py
from django.conf.urls import url
from lab import views
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
       #url(r'^$', views.lab_list, name='lab_list'),
       url(r'^lab/(?P<lab_id>\d+)/(?P<slug>[\w-]+)/detail/$', views.lab_detail, name='lab_detail'),
       url(r'^lab/manage/add/$', views.add_edit_lab, name='add_lab'),
       url(r'^lab/manage/(?P<lab_id>\d+)/edit/$', views.add_edit_lab, name='edit_lab'),
       url(r'^lab/member/add/$', views.add_member, name='add_member'),
       url(r'^lab/member/delete/$', views.delete_member, name='delete_member'),
       url(r'^lab/logo/upload/$', views.upload_logo, name='upload_logo'),
       url(r'^lab/(?P<lab_id>\d+)/payment/$', views.payment, name='payment'),
       url(r'^lab/(?P<lab_id>\d+)/payment/complete/$', views.payment_complete, name='payment_complete'),
       url(r'^lab/(?P<lab_id>\d+)/balancer/$', views.manage_orderings, name='lab_balancer'),
       url(r'^lab/(?P<lab_id>\d+)/balancer/delete/$', views.delete_order, name='lab_balancer_delete_order'),
       url(r'^lab/(?P<lab_id>\d+)/balancer/add/$', views.balancer_add, name='lab_balancer_order_add'),
       url(r'^lab/(?P<lab_id>\d+)/balancer/update/$', views.balancer_update, name='lab_balancer_order_update'),
       url(r'^lab/(?P<lab_id>\d+)/balancer/edit/(?P<balance_id>\d+)/$', views.balancer_edit,
           name='lab_balancer_order_edit'),
       url(r'^balance/(?P<slug>\w+)/$', views.balancer_url, name='lab_balancer_url'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

xperiment/lab/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _

from model_utils.models import TimeStampedModel

from core.utils import unique_slugify

from .utils import ROLE_CHOICES, ROLE_MEMBER


class Lab(TimeStampedModel):
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    # TODO Address field
    website = models.URLField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    logo = models.URLField(max_length=1024, null=True, blank=True)
    balance = models.FloatField(default=0)

    def __unicode__(self):
        return self.name

    @property
    def scientists(self):
        return self.labscientist_set.all()

    def add_scientist(self, email, scientist, role=ROLE_MEMBER):
        try:
            ls = LabScientist.objects.get(lab=self, email=email, scientist=scientist)
            ls.role = role
        except LabScientist.DoesNotExist:
            ls = LabScientist(lab=self, email=email, scientist=scientist, role=role)

        ls.save()

    def save(self, **kwargs):
        slug = '%s' % (self.name)
        unique_slugify(self, slug)
        super(Lab, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('lab_detail', args=[self.id, self.slug])

    def scientist_belong_this(self, user):
        return self.labscientist_set.filter(scientist = user).count() > 0


class LabScientist(TimeStampedModel):
    role = models.IntegerField(choices=ROLE_CHOICES, default=ROLE_MEMBER)
    lab = models.ForeignKey(Lab, null=True,  on_delete=models.SET_NULL)
    email = models.EmailField()
    scientist = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ('lab', 'email', 'scientist')

    def __unicode__(self):
        return self.email


class StudyBalancer(TimeStampedModel):
    lab = models.ForeignKey(Lab, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, default=uuid4().hex)
    randomness = models.FloatField(default=.2)


class PaymentRecord(TimeStampedModel):
    lab = models.ForeignKey(Lab, verbose_name=_(u'Lab'), null=True, on_delete=models.SET_NULL)
    scientist = models.ForeignKey(User, verbose_name=_(u'Scientist'), null=True, on_delete=models.SET_NULL)
    amount = models.FloatField(default=0, verbose_name=_(u'Amount'))
    description = models.TextField(verbose_name=_(u'Description'), max_length=1024, null=True, blank=True)

xperiment/scientist/models.py
from django.contrib.auth import user_logged_in
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from model_utils.models import TimeStampedModel


class Profile(TimeStampedModel):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=20, blank=True, null=True)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    # TODO Address field
    website = models.URLField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    avatar = models.URLField(null=True, blank=True)
    is_scientist = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.email

    def get_full_name(self):
        return self.fullname if self.fullname else self.user.username

    def get_absolute_url(self):
        return reverse('scientist_detail', args=[self.user.username])


def check_userprofile(sender, request, user, **kwargs):
    try:
        profile = user.profile
    except:
        Profile(user=user).save()


user_logged_in.connect(check_userprofile)

xperiment/lab/forms.py
from django.forms import ModelForm

from .models import Lab

class LabForm(ModelForm):

    class Meta:
        model = Lab
        exclude = (
            'creator',
            'slug',
            'logo',
            'balance',
        )

xperiment/lab/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.messages import success
from django.core import serializers
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from allauth.account.signals import user_signed_up
from allauth.account.utils import send_email_confirmation

from allauth.account.models import EmailAddress
from allauth.account import app_settings

from attachment.views import attachment_upload
from balancer.views import rand_from_balancer
from balancer.models import BalanceItem
from core.utils import json_result, generate_password, send_email
from scientist.models import Profile
from .forms import LabForm
from .models import Lab, LabScientist, PaymentRecord, StudyBalancer
from .utils import ROLE_CREATOR


def lab_list(request, template='lab/lab_list.html', extra_context=None):
    context = {}

    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


def lab_detail(request, lab_id, slug, template='lab/lab_detail.html', extra_context=None):
    lab = get_object_or_404(Lab, id=lab_id)
    if slug != lab.slug:
        return HttpResponseRedirect(reverse_lazy('lab_detail', args=[lab.id, lab.slug]))

    context = {
        'lab': lab,
    }

    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def add_edit_lab(request, lab_id=None, template='lab/add_edit_lab.html', extra_context=None):
    lab = None
    action = 'Add'
    if lab_id:
        lab = get_object_or_404(Lab, id=lab_id, creator=request.user)
        action = 'Edit'

    form = LabForm(instance=lab)

    if request.method == 'POST':
        form = LabForm(instance=lab, data=request.POST, files=request.FILES)
        if form.is_valid():
            lab = form.save(commit=False)
            lab.creator = request.user
            lab.save()
            lab.add_scientist(request.user.email, request.user, ROLE_CREATOR)
            success(request, _(u'%s has been saved.' % lab.name))

            return HttpResponseRedirect(reverse_lazy('lab_detail', args=[lab.id, lab.slug]))

    context = {
        'form': form,
        'action': action,
    }

    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def add_member(request):
    lab_id = request.POST.get('lab_id', None)
    member_email = request.POST.get('member_email', None)
    lab = get_object_or_404(Lab, pk=lab_id)

    new_user = None
    temp_password = None
    try:
        user = User.objects.get(email=member_email)
    except User.DoesNotExist:
        temp_password = generate_password(8)
        user = User.objects.create_user(username=member_email, email=member_email, password=temp_password)
        Profile(user=user, is_scientist=True).save()
        if not hasattr(user, 'backend'):
            user.backend = 'django.contrib.auth.backends.ModelBackend'
        user_signed_up.send(sender=user.__class__,
                            request=request,
                            user=user)
        has_verified_email = EmailAddress.objects.filter(user=user,
                                                         verified=True).exists()
        if app_settings.EMAIL_VERIFICATION == app_settings.EmailVerificationMethod.NONE:
            pass
        else:
            if not has_verified_email:
                send_email_confirmation(request, user, signup=False)
        new_user = user

    if lab.labscientist_set.filter(email=member_email, scientist=user).count() > 0:
        result = {'status': 'warning', 'message': 'User already exist'}
    else:
        lab_scientist = LabScientist(lab=lab, email=user.email, scientist=user)
        lab_scientist.save()
        scientist = lab_scientist.scientist
        send_email(
            subject='%s added you to lab %s as a member' % (lab.creator.profile.get_full_name(), lab.name),
            to_emails=[user.email],
            template_name='lab/email/add_member_email.html',
            context={
                'lab': lab,
                'site_url': request.get_host(),
                'new_user': new_user,
                'temp_password': temp_password,
            }
        )
        result = {
            'status': 'success',
            'member_email': member_email,
            'username': scientist.username if scientist else lab_scientist.email,
            'fullname': scientist.profile.get_full_name() if scientist else lab_scientist.email,
            'role': lab_scientist.get_role_display(),
            'url': '/static/images/avator.png',
            'created': lab_scientist.created.strftime('%b. %d, %y, %I:%M %p.'),
        }

    return json_result(request, result)


@login_required
def delete_member(request):
    ls_list = None
    lab_id = request.POST.get('lab_id', None)
    lab = get_object_or_404(Lab, pk=lab_id)
    member_email = request.POST.get('member_email', None)

    if member_email:
        ls_list = LabScientist.objects.filter(Q(lab__id=lab_id),
                                              Q(scientist__email=member_email) | Q(email=member_email))

    if ls_list and len(ls_list) > 0:
        ls_list[0].delete()
        send_email(
            subject='%s removed you from lab %s' % (lab.creator.profile.get_full_name(), lab.name),
            to_emails=[member_email],
            template_name='lab/email/remove_member_email.html',
            context={
                'lab': lab,
                'site_url': request.get_host(),
            }
        )
        result = {'status': 'success', 'member_email': member_email}
    else:
        result = {'status': 'error', 'message': 'The user does not exist in the lab'}

    return json_result(request, result)


@login_required
def upload_logo(request):
    '''
    Upload logo
    :param request:
    :return:
    '''

    lab_id = request.GET.get('lab_id')
    try:
        lab = Lab.objects.get(pk=lab_id)
        data = attachment_upload(request, lab)
        lab.logo = data['url']
        lab.save()
        result = {'status': 'success', 'thumbnail_url': lab.logo}
    except Lab.DoesNotExist:
        result = {'status': 'error', 'message': 'The lab does not exist'}
    except Exception as e:
        result = {'status': 'error', 'message': e.message}
    return json_result(request, result)


@login_required
def payment(request, lab_id, template='lab/payment.html', extra_context=None):
    lab = get_object_or_404(Lab, id=lab_id, creator=request.user)

    #TODO: Add paypal form

    context = {
        'lab': lab,
    }

    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def payment_complete(request, lab_id):
    amount = float(request.POST.get('amount'))
    lab = get_object_or_404(Lab, id=lab_id)
    lab.balance += amount
    lab.save()
    PaymentRecord(lab=lab, scientist=request.user, amount=amount).save()
    return HttpResponseRedirect(reverse_lazy('lab_detail', args=[lab.id, lab.slug]))



@login_required
def manage_orderings(request, lab_id, template='lab/balancer.html', extra_context=None):
    context = construct_table_info(lab_id)
    context['url'] = request.scheme + '://' + request.get_host() + '/balance/'
    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


def construct_table_info(lab_id):
    order_list = serializers.serialize('json', StudyBalancer.objects.filter(lab_id=lab_id).order_by('-created'),
                                       fields=('name', 'slug', 'randomness'))

    print(order_list)

    return {'order_list': order_list}


@login_required
def delete_order(request, lab_id):
    order_ids = request.POST.getlist('order_ids[]', None)

    if order_ids and len(order_ids) > 0:
        try:
            StudyBalancer.objects.filter(pk__in=order_ids, lab_id=lab_id).delete()
            delete_balanceItems(lab_id, order_ids)
            result = {
                'status': 'success',
                'objects': []
            }
            result.update(construct_table_info(lab_id))
        except Exception as e:
            result = {
                'status': 'error',
                'message': e
            }
    else:
        result = {
            'status': 'error',
            'message': 'Parameters order ids can not be empty'
        }

    return json_result(request, result)


def delete_balanceItems(lab_id, order_ids):
    delete_list = []
    for id in order_ids:
        delete_list.append(balance_item_id_generate(lab_id, id))
    BalanceItem.objects.filter(group_id__in=delete_list).delete()


@login_required
def balancer_update(request, lab_id):

    batch_pk = request.POST.get('batch_id', None)
    randomness = request.POST.get('randomness', None)

    if batch_pk and randomness:
        try:
            result = {
                'status': 'success',
                'items': []
            }

            balance_item = StudyBalancer.objects.get(lab_id=lab_id, pk=batch_pk)
            balance_item.randomness = float(randomness)
            balance_item.save()

        except Exception as e:
            result = {
                'status': 'error',
                'message': e
            }
    else:
        result = {
            'status': 'error',
            'message': 'batch id can not be empty'
        }

    return json_result(request, result)


@login_required
def balancer_add(request, lab_id):
    batch_name = request.POST.get('batch_name', None)

    if batch_name:
        try:
            result = {
                'status': 'success',
                'items': []
            }

xperiment/templates/lab/_upload_logo.html
{% load i18n util_tags %}

<div id="upload_logo_container" data-lab-id="{{ lab.id }}">
    <div class="lab-logo">
        <a class="change-logo" href="#">
            {% if lab.logo %}
                <img src="{{ lab.logo }}" class="img-thumbnail user-avatar" alt="{{ lab.name }}">
            {% else %}
                <img data-src="holder.js/200x200/{{ 'sky,vine,lava,gray,industrial,social'|split:","|random }}/text:{{ lab.name }}"
                     class="img-thumbnail" alt="{{ lab.name }}">
            {% endif %}
            {% if user == lab.creator %}
                <span id="upload_logo" class="change-logo-text">{% trans "Change Logo" %}</span>
            {% endif %}
        </a>
    </div>
</div>

xperiment/templates/lab/_upload_logo_js.html
<script type="text/javascript" src="{{ STATIC_URL }}js/plupload/plupload.full.min.js"></script>

<script type="text/javascript">
    $(function () {
        var uploader = new plupload.Uploader({
            runtimes: 'html5,flash,silverlight,html4',
            browse_button: 'upload_logo',
            url: "{% url 'upload_logo' %}",
            flash_swf_url: "{{ STATIC_URL }}js/plupload/Moxie.swf",
            silverlight_xap_url: '{{ STATIC_URL }}js/plupload/Moxie.xap',
            filters: {
                max_file_size: '10mb',
                mime_types: [
                    {title: "Image files", extensions: "jpg,gif,png"}
                ]
            },
            headers: {
                "ACCEPT": "application/json",
                "X-CSRFToken": $.cookie("csrftoken")
            },
            init: {
                FilesAdded: function (up, files) {
                    var request_url = up.settings.url;
                    up.settings.url = request_url + "?lab_id=" + String($("#upload_logo_container").data("lab-id"));
                    up.start();
                    up.refresh(); // Reposition Flash/Silverlight
                    up.settings.url = request_url;
                },

                FileUploaded: function (up, file, info) {
                    var obj = $.parseJSON(info.response);
                    if (obj.status == "success") {
                        $("#upload_logo_container").find("img").attr("src", obj.thumbnail_url);
                    } else {
                        alert(obj.message);
                    }
                },

                Error: function (up, err) {
                    alert(err.message);
                    up.refresh(); // Reposition Flash/Silverlight
                }
            }
        });

        uploader.init();
    });
</script>

xperiment/templates/lab/add_edit_lab.html
{% extends "base.html" %}

{% load i18n bootstrap3 %}

{% block title %}{% trans "Lab" %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h3>
                    {{ action }} Lab
                </h3>
            </div>
            <div class="well well-lg">
                <form class="form-horizontal" method="POST" action="" role="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "ok" %} Submit
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

xperiment/templates/lab/invite_member.html
{% extends "base.html" %}

{% load i18n static %}

{% block title %}{% trans "Lab" %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h3>
                    {{ action }} Lab
                </h3>
            </div>
            <div class="well well-lg">
                <form class="form-horizontal" method="POST" action="" role="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "ok" %} Submit
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'css/TagContacts.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/TagContacts.js' %}"></script>
    <script src="{% static 'js/invite_member.js' %}"></script>
{% endblock %}

xperiment/templates/lab/lab_detail.html
{% extends "base.html" %}

{% load i18n static util_tags %}

{% block title %}{% trans "Lab" %}{% endblock %}

{% block content %}
    <div class="row lab">
        <div class="col-md-8 col-md-offset-2">
            <div class="row">
                <div class="col-md-8 lab-main">
                    <!-- Lab Bio -->
                    <div class="lab-bio">
                        <div class="page-header">
                            <h3>
                                <i class="glyphicon glyphicon-home"></i>
                                {{ lab.name }}
                            </h3>
                            <h4><a href="{% url "experiment_manage" lab.id %}"><i class="glyphicon glyphicon-wrench"></i> <strong>{% trans "Manage experiments" %}</strong></a></h4>
                        </div>

                        <div>
                            {% if lab.email %}
                                <p>
                                    <i class="glyphicon glyphicon-envelope"></i>
                                    {{ lab.email }}
                                </p>
                            {% endif %}
                            {% if lab.phone %}
                                <p>
                                    <i class="glyphicon glyphicon-phone"></i>
                                    {{ lab.phone }}
                                </p>
                            {% endif %}
                            {% if lab.website %}
                                <p>
                                    <i class="glyphicon glyphicon-globe"></i>
                                    {{ lab.website }}
                                </p>
                            {% endif %}
                        </div>

                        {% if lab.description %}
                            <div>
                                <blockquote>
                                    {{ lab.description|capfirst }}
                                </blockquote>
                            </div>
                        {% endif %}

                        {% if user == lab.creator %}
                            <div class="lab-actions">
                                <a href="{% url "edit_lab" lab.id %}" class="btn btn-default btn-block">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    {% trans "Change name and detail" %}
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <!-- End of lab bio -->

                    <!-- Members -->
                    <div class="lab-labs">
                        <div class="page-header">
                            <h4>
                                <i class="glyphicon glyphicon-user"></i>
                                {% trans "Scientists" %}
                            </h4>
                        </div>

                        <input id="lab_id" type="hidden" value="{{ lab.id }}">

                        <!-- Member list -->
                        <div id="member_list">
                            {% for scientist in lab.scientists %}
                                <div class="row media">
                                    <div class="col-md-10">
                                        <div class="media">
                                            <a class="pull-left" href=" {% if scientist.scientist %}{% url "scientist_detail" scientist.scientist.username %}{% endif %}">
                                                {% if scientist.scientist.profile.avatar %}
                                                    <img src="{{ scientist.scientist.profile.avatar }}" class="img-thumbnail lab-logo-small"
                                                         alt="{{ scientist.scientist.profile.fullname|default:scientist.email }}">
                                                {% else %}
                                                    <img data-src="holder.js/50x50/{{ 'sky,vine,lava,gray,industrial,social'|split:","|random }}/text:{{ scientist.scientist.profile.fullname|default:scientist.email }}"
                                                         class="img-thumbnail" alt="{{ scientist.scientist.profile.fullname|default:scientist.email }}">
                                                {% endif %}
                                            </a>

                                            <div class="media-body">
                                                <h5 class="media-heading">
                                                    <a href="
                                                            {% if scientist.scientist %}{% url "scientist_detail" scientist.scientist.username %}{% endif %}">
                                                        {{ scientist.scientist.profile.fullname|default:scientist.email }}
                                                    </a> ({{ scientist.get_role_display }})
                                                </h5>
                                                <i class="glyphicon glyphicon-time"></i> {% trans "Joined at" %} {{ scientist.created|date:"M. d, Y, h:i A." }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        {% if user == lab.creator and scientist.get_role_display != "Creator" %}
                                            <a name="delete_member" href="#" class="btn"
                                               data-member-email="{{ scientist.scientist.email|default:scientist.email }}"><i
                                                    class="icon-remove-circle"></i></a>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        <!-- end of member list -->

                        {% if user == lab.creator %}
                            <div class="lab-actions">
                                <a id="invite_member" class="btn btn-default btn-block" href="#">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    {% trans "Invite new members" %}
                                </a>
                            </div>
                        {% endif %}

                        <div id="input_member" class="lab-actions" style="display: none;">
                            <div class="row">
                                <div class="col-md-3"><span class="lab-member">{% trans "Input Email" %}:</span></div>
                                <div class="col-md-9">
                                    <div id="tag_contact"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- End of Members -->

                    <div class="lab-main-footer"></div>

                </div>

                <div class="col-md-4 lab-sidebar">
                    {% include "lab/_upload_logo.html" %}

                    <div class="lab-summary">

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_css %}
    <link href="{% static 'css/TagContacts.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script id="tpl_member" type="text/template">
        <div class="row media">
            <div class="col-md-10">
                <div class="media">
                    <a class="pull-left" href="/scientist/<%= username %>/">
                        <img class="media-object" src="<%= url %>"
                             alt="<%= fullname %>">
                    </a>

                    <div class="media-body">
                        <h5 class="media-heading">
                            <a href="/scientist/<%= username %>/">
                                <%= fullname %>
                            </a> (<%= role %>)
                        </h5>
                        <i class="glyphicon glyphicon-time"></i> {% trans "Joined at" %} <%= created %>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <a name="delete_member" href="#" class="btn" data-member-email="<%= member_email %>"><i class="icon-remove-circle"></i></a>
            </div>
        </div>
    </script>

    <script src="{% static 'js/TagContacts.js' %}"></script>
    <script src="{% static 'js/invite_member.js' %}"></script>

    {% include "lab/_upload_logo_js.html" %}
{% endblock %}

xperiment/templates/lab/lab_list.html
{% extends "base.html" %}

xperiment/templates/lab/upload_swf.html
{% load i18n staticfiles account bootstrap3 lab_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% trans "Upload Swf" %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>

<div class="container upload_swf_form">
    <form class="form-horizontal" method="POST" action="{% url "upload_swf_submit" lab.id %}" role="form">
        {% csrf_token %}

        <div class="form-group">
            <label>Title</label>
            <input class="form-control" id="id_title" maxlength="255" name="title" type="text">
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea class="form-control" cols="40" id="id_description" name="description" rows="10"></textarea>
        </div>

        <div class="form-group">
            <button id="choose_swf" type="button" class="btn btn-success btn-block">
                Upload a new swf
            </button>
        </div>

        <div class="form-group">
            <span id="upload_swf_message" class="label label-success" style="display: none;">Upload swf file successfully</span>
        </div>

        <input type="hidden" id="id_swf_id" name="swf_id" value="">

        <div class="form-group pull-right">
            <button id="btn_upload_swf_submit" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-ok"></span> Submit
            </button>

            <button id="btn_upload_swf_close" type="button" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span> Close
            </button>
        </div>
    </form>
</div>

</body>
</html>